import os

GF_SECURITY_ADMIN_USER=os.environ['GF_SECURITY_ADMIN_USER']
GF_SECURITY_ADMIN_PASSWORD=os.environ['GF_SECURITY_ADMIN_PASSWORD']

SOURCE_DB_URL = os.environ['REDATA_SOURCE_DB_URL']
METRICS_DB_URL = os.environ['REDATA_METRICS_DB_URL']