"""Generate checks and metric tables

Revision ID: 1ebc9777727b
Revises: 3144636397e6
Create Date: 2021-02-15 13:19:13.271771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ebc9777727b'
down_revision = '3144636397e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('columns', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('metrics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['monitored_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_created_at'), 'checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_checks_table_id'), 'checks', ['table_id'], unique=False)
    op.create_table('metric',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('table_column', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['monitored_table.id'], ),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_index(op.f('ix_metric_check_id'), 'metric', ['check_id'], unique=False)
    op.create_index(op.f('ix_metric_created_at'), 'metric', ['created_at'], unique=False)
    op.create_index(op.f('ix_metric_table_id'), 'metric', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_table_id'), table_name='metric')
    op.drop_index(op.f('ix_metric_created_at'), table_name='metric')
    op.drop_index(op.f('ix_metric_check_id'), table_name='metric')
    op.drop_table('metric')
    op.drop_index(op.f('ix_checks_table_id'), table_name='checks')
    op.drop_index(op.f('ix_checks_created_at'), table_name='checks')
    op.drop_table('checks')
    # ### end Alembic commands ###
