"""Adjust constraints and add data_source_id

Revision ID: 21393f7d8566
Revises: 184924ecd052
Create Date: 2021-03-31 08:47:02.719825

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "21393f7d8566"
down_revision = "184924ecd052"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checks",
        "metrics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.drop_constraint("checks_table_id_fkey", "checks", type_="foreignkey")
    op.create_foreign_key(
        "checks_table_id_fkey",
        "checks",
        "monitored_table",
        ["table_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column("data_source", sa.Column("created_at", sa.TIMESTAMP(), nullable=True))
    op.create_index(
        op.f("ix_data_source_created_at"), "data_source", ["created_at"], unique=False
    )
    op.drop_constraint("metric_check_id_fkey", "metric", type_="foreignkey")
    op.drop_constraint("metric_table_id_fkey", "metric", type_="foreignkey")
    op.create_foreign_key(
        "metric_table_id_fkey",
        "metric",
        "monitored_table",
        ["table_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "metric_check_id_fkey",
        "metric",
        "checks",
        ["check_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "monitored_table", sa.Column("data_source_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_monitored_table_data_source_id"),
        "monitored_table",
        ["data_source_id"],
        unique=False,
    )
    op.create_foreign_key(
        "table_data_source_id_fkey",
        "monitored_table",
        "data_source",
        ["data_source_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("monitored_table", "source_db")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitored_table",
        sa.Column("source_db", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "table_data_source_id_fkey", "monitored_table", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_monitored_table_data_source_id"), table_name="monitored_table"
    )
    op.drop_column("monitored_table", "data_source_id")
    op.drop_constraint("metric_check_id_fkey", "metric", type_="foreignkey")
    op.drop_constraint("metric_table_id_fkey", "metric", type_="foreignkey")
    op.create_foreign_key(
        "metric_table_id_fkey", "metric", "monitored_table", ["table_id"], ["id"]
    )
    op.create_foreign_key(
        "metric_check_id_fkey", "metric", "checks", ["check_id"], ["id"]
    )
    op.drop_index(op.f("ix_data_source_created_at"), table_name="data_source")
    op.drop_column("data_source", "created_at")
    op.drop_constraint("checks_table_id_fkey", "checks", type_="foreignkey")
    op.create_foreign_key(
        "checks_table_id_fkey", "checks", "monitored_table", ["table_id"], ["id"]
    )
    op.alter_column(
        "checks",
        "metrics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
