"""Add delete cascade for alerts

Revision ID: 21a21ae32481
Revises: 21393f7d8566
Create Date: 2021-04-07 17:08:09.395010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "21a21ae32481"
down_revision = "21393f7d8566"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "alerts_alert", "table_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_index(
        op.f("ix_alerts_alert_table_id"), "alerts_alert", ["table_id"], unique=False
    )
    op.drop_constraint("alerts_alert_table_id_fkey", "alerts_alert", type_="foreignkey")
    op.create_foreign_key(
        None,
        "alerts_alert",
        "monitored_table",
        ["table_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "alerts_alert", type_="foreignkey")
    op.create_foreign_key(
        "alerts_alert_table_id_fkey",
        "alerts_alert",
        "monitored_table",
        ["table_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_alerts_alert_table_id"), table_name="alerts_alert")
    op.alter_column(
        "alerts_alert", "table_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
