"""Add created_at and require metric

Revision ID: 2fc7f529c614
Revises: 184924ecd052
Create Date: 2021-03-28 10:23:29.470359

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2fc7f529c614"
down_revision = "184924ecd052"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checks",
        "metrics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.add_column("data_source", sa.Column("created_at", sa.TIMESTAMP(), nullable=True))
    op.create_index(
        op.f("ix_data_source_created_at"), "data_source", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_source_created_at"), table_name="data_source")
    op.drop_column("data_source", "created_at")
    op.alter_column(
        "checks",
        "metrics",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
