"""Add user model

Revision ID: 793dc222e3ff
Revises: e43463587d74
Create Date: 2021-02-22 16:41:18.091007

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "793dc222e3ff"
down_revision = "e43463587d74"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("login", sa.String(length=80), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.drop_index("ix_metric_table_column", table_name="metric")
    op.create_index(
        op.f("ix_metric_table_column"), "metric", ["table_column"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metric_table_column"), table_name="metric")
    op.create_index("ix_metric_table_column", "metric", ["metric"], unique=False)
    op.drop_table("user")
    # ### end Alembic commands ###
