"""Add port to data source

Revision ID: 8be0b8538d61
Revises: ba31baadc449
Create Date: 2021-03-06 15:09:31.384668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8be0b8538d61"
down_revision = "ba31baadc449"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_source", sa.Column("port", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_source", "port")
    # ### end Alembic commands ###
