"""empty message

Revision ID: 9bdab56c899b
Revises: 2fc7f529c614
Create Date: 2021-03-30 09:33:55.898954

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9bdab56c899b"
down_revision = "2fc7f529c614"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitored_table", sa.Column("data_source_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_monitored_table_data_source_id"),
        "monitored_table",
        ["data_source_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "monitored_table",
        "data_source",
        ["data_source_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "monitored_table", type_="foreignkey")
    op.drop_index(
        op.f("ix_monitored_table_data_source_id"), table_name="monitored_table"
    )
    op.drop_column("monitored_table", "data_source_id")
    # ### end Alembic commands ###
