"""Add run

Revision ID: ba31baadc449
Revises: fd3174b5f939
Create Date: 2021-02-28 09:29:41.946490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba31baadc449"
down_revision = "fd3174b5f939"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("for_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("run_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run")
    # ### end Alembic commands ###
