{
 "title": "__REPLACE__",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "new_records summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "new_record_created",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "none",
   "valueName": "avg",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": "__TO_REPLACE__"
  },
  {
   "title": "new_records_by_day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": "__TO_REPLACE__"
  },
  {
   "title": "time_since_last_record_created",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": "__TO__REPLACE__"
  },
  { "title": "schema_changes summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "metrics_data_volume schema_changes",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "\n        SELECT\n            created_at AS \"time\",\n            operation,\n            column_name,\n            column_type\n        FROM metrics_table_schema_changes\n        WHERE\n            table_name = 'metrics_data_volume' and\n            $__timeFilter(created_at)\n        ORDER BY 1\n        "
    }
   ]
  },
  {
   "title": "current_table_schema",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  col.*\nFROM\n  metrics_table_metadata,\n  jsonb_to_recordset(schema->'columns') col(name text, type text)\nWHERE\n  table_name = 'metrics_data_values'"
    }
   ]
  },
  { "title": "column_specific_stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "metrics_data_volume:count check_avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "\n        select\n            created_at as time, time_interval, check_value\n        from\n            metrics_data_values\n        where\n            table_name = 'metrics_data_volume' and column_name = 'count' and check_name='check_avg'\n        order by\n        1\n    "
    }
   ]
  }
 ]
}